###
### SERVICES
###
---
apiVersion: v1
kind: Service
metadata:
  name: clouddriver
  labels:
    app: spinnaker
    component: clouddriver
spec:
  ports:
  - port: 7002
  selector:
    component: clouddriver
---
apiVersion: v1
kind: Service
metadata:
  name: orca
  labels:
    app: spinnaker
    component: orca
spec:
  ports:
  - port: 8083
  selector:
    component: orca
---
apiVersion: v1
kind: Service
metadata:
  name: gate
  labels:
    app: spinnaker
    component: gate
spec:
  ports:
  - port: 8084
  selector:
    component: gate
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rush
  labels:
    app: spinnaker
    component: rush
spec:
  ports:
  - port: 8085
  selector:
    component: rush
---
apiVersion: v1
kind: Service
metadata:
  name: rosco
  labels:
    app: spinnaker
    component: rosco
spec:
  ports:
  - port: 8086
  selector:
    component: rosco
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: spinnaker
    component: echo
spec:
  ports:
  - port: 8089
  selector:
    component: echo
---
apiVersion: v1
kind: Service
metadata:
  name: front50
  labels:
    app: spinnaker
    component: front50
spec:
  ports:
  - port: 8080
  selector:
    component: front50
---
apiVersion: v1
kind: Service
metadata:
  name: deck
  labels:
    app: spinnaker
    component: deck
spec:
  ports:
  - port: 9000
  selector:
    component: deck
  type: LoadBalancer
