server:
  port: ${services.clouddriver.port:7002}
  address: ${services.clouddriver.host:localhost}

#circular
#services:
#  front50:
#    baseUrl: ${services.front50.baseUrl:localhost:8080}

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

default:
  account:
    env: ${providers.aws.primaryCredentials.name}

aws:
  enabled: ${providers.aws.enabled:false}
  defaults:
    iamRole: ${provider.aws.defaultIAMRole:BaseIAMRole}
  defaultRegions:
    - name: ${providers.aws.defaultRegion:us-east-1}
  defaultFront50Template: ${services.front50.baseUrl}

  # Credentials are passed either as environment variables or through
  # a standard AWS file $HOME/.aws/credentials
  # See providers.aws.primaryCredentials in spinnaker.yml for more
  # info on setting environment variables.
  #
  # TODO(ewiseblatt):
  # This only works for root credentials, which you arent supposed to use.
  # I havent been able to figure out how to get normal user accounts to work.
  # I'm leaving this broken for now hoping that once this gets mainlined some
  # body else will be able to fix it.

google:
  enabled: ${providers.google.enabled:false}

  accounts:
    - name: ${providers.google.primaryCredentials.name}
      project: ${providers.google.primaryCredentials.project}
      jsonPath: ${providers.google.primaryCredentials.jsonPath}

cf:
  enabled: ${providers.cf.enabled:false}

  accounts:
    - name: ${providers.cf.primaryCredentials.name}
      api: ${providers.cf.primaryCredentials.api}
      console: ${providers.cf.primaryCredentials.console}
      org: ${providers.cf.defaultOrg}
      space: ${providers.cf.defaultSpace}
      username: ${cf.account.name:}
      password: ${cf.account.password:}

credentials:
  primaryAccountTypes: ${providers.aws.primaryCredentials.name}, ${providers.google.primaryCredentials.name}, ${providers.cf.primaryCredentials.name}
  challengeDestructiveActionsEnvironments: ${providers.aws.primaryCredentials.name}, ${providers.google.primaryCredentials.name}, ${providers.cf.primaryCredentials.name}
